<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20for%20PyTorch/PyTorch%20Basics/8%20exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. 2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.



In [24]:
import torch
x = torch.ones(3,3,dtype=float)
x = x.unsqueeze(0)
print(x, x.shape, sep= '\n')

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64) torch.Size([1, 3, 3])


####2. 이전 텐서에 추가한 차원을 삭제하세요.

In [25]:
x = x.squeeze(0)
print(x, x.shape, sep= '\n')

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([3, 3])


####3. 범위가 [3,7)이고 크기가 5x3인 랜덤한 텐서를 만드세요.

In [34]:
x = torch.randint(3,7 ,size=(5,3))
x

tensor([[6, 4, 5],
        [6, 6, 5],
        [5, 4, 4],
        [6, 5, 3],
        [3, 3, 5]])

####4. 정규 분포(평균 = 0, 표준편차 = 1)를 사용해 텐서를 만드세요.

In [35]:
x = torch.randn(3,3)
x

tensor([[-0.3713, -0.2407,  0.8265],
        [-0.5598, -0.3760, -0.7871],
        [ 0.9566,  0.9230,  1.6625]])

####5. 텐서 torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스를 추출하세요.

In [46]:
x = torch.Tensor([1,1,1,0,1])
[i for i in range(len(x)) if x[i] != 0]

[0, 1, 2, 4]

####6. 크기가 (3,1)인 랜덤한 텐서를 만들고 네 벌을 복사해서 쌓으세요.

In [55]:
x = torch.Tensor(3,1)
print(f'1) concat\n shape = {torch.concat([x,x,x,x]).shape}, \n', torch.concat([x,x,x,x]))
print(f'2) stack\n shape = {torch.stack([x,x,x,x]).shape} \n', torch.stack([x,x,x,x]))

1) concat
 shape = torch.Size([12, 1]), 
 tensor([[2.6612e-34],
        [0.0000e+00],
        [1.5975e-43],
        [2.6612e-34],
        [0.0000e+00],
        [1.5975e-43],
        [2.6612e-34],
        [0.0000e+00],
        [1.5975e-43],
        [2.6612e-34],
        [0.0000e+00],
        [1.5975e-43]])
2) stack
 shape = torch.Size([4, 3, 1]) 
 tensor([[[2.6612e-34],
         [0.0000e+00],
         [1.5975e-43]],

        [[2.6612e-34],
         [0.0000e+00],
         [1.5975e-43]],

        [[2.6612e-34],
         [0.0000e+00],
         [1.5975e-43]],

        [[2.6612e-34],
         [0.0000e+00],
         [1.5975e-43]]])


####7. 2차원 행렬 두개(a=torch.rand(4,5), b=torch.rand(5,4))의 배치 행렬 곱셈을 계산하세요.

In [59]:
a=torch.rand(4,5)
b=torch.rand(5,4)
torch.bmm(a.unsqueeze(0), b.unsqueeze(0))

tensor([[[1.3116, 1.8257, 1.5781, 1.1614],
         [0.5208, 0.8826, 0.8767, 0.7941],
         [0.4365, 1.3839, 0.8346, 0.8573],
         [0.4568, 1.0517, 0.9882, 0.8953]]])

####8. 3차원 행렬(a=torch.rand(3,4,5))과 2차원 행렬(b=torch.rand(5,4))의 배치 행렬 곱셈을 계산하세요.

In [61]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)
torch.bmm(a, torch.stack((b,b,b)))

tensor([[[0.9056, 0.3024, 0.9570, 1.3551],
         [1.6697, 1.3101, 1.0434, 1.5324],
         [1.6793, 1.3651, 0.9479, 2.2392],
         [1.9483, 1.4645, 0.9538, 2.1205]],

        [[1.7722, 1.0391, 1.4213, 2.4737],
         [1.7020, 1.1598, 1.0665, 2.3051],
         [0.8185, 0.4089, 0.6969, 1.1161],
         [0.9289, 0.7093, 0.7615, 1.1356]],

        [[1.1827, 1.1152, 0.6207, 1.5988],
         [1.8095, 1.0956, 1.1760, 1.7993],
         [1.2649, 1.1985, 0.7081, 1.1723],
         [1.1790, 0.8969, 0.6635, 1.5711]]])