<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20with%20PyTorch/PyTorch%20Basics/Tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
def describe(x):
  print('타입: {}'.format(x.type()))
  print('크기: {}'.format(x.shape))
  print('값: \n{}'.format(x))
  print('\n\n')

In [15]:
x  = torch.randn(2,3)
print('#  torch.randn(2,3)')
describe(x)

print('#  torch.add(x,x)')
describe(torch.add(x,x))

print('#  x + x')
describe(x + x)

#  torch.randn(2,3)
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.3337,  0.7917,  1.9776],
        [-0.2179, -0.4516, -0.8093]])



#  torch.add(x,x)
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.6673,  1.5833,  3.9553],
        [-0.4357, -0.9032, -1.6185]])



#  x + x
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.6673,  1.5833,  3.9553],
        [-0.4357, -0.9032, -1.6185]])





In [26]:
#torch.arange(): [기본값 0,parameter) 범위를 기본값 1 단위로 증가하는 1차원 텐서를 만듦
x = torch.arange(6)
describe(x)

x = torch.arange(1,13,2)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])



타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([ 1,  3,  5,  7,  9, 11])





In [28]:
#.view(): 텐서와 동일한 값을 공유하는 새로운 텐서를 만드는 메서드
x = x.view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1,  3,  5],
        [ 7,  9, 11]])





In [35]:
#2차원 텐서에서는 행의 인덱스 = 0 열의 인덱스 = 1
print('#  x')
describe(x)

print('#  torch.sum(x, dim=0)')
describe(torch.sum(x, dim=0))

print('#  torch.sum(x, dim=-1)')
describe(torch.sum(x, dim=-1))

print('#  torch.transpose(x, 0, 1)')
describe(torch.transpose(x, 0, 1))

#  x
타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1,  3,  5],
        [ 7,  9, 11]])



#  torch.sum(x, dim=0)
타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([ 8, 12, 16])



#  torch.sum(x, dim=-1)
타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 9, 27])



#  torch.transpose(x, 0, 1)
타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[ 1,  7],
        [ 3,  9],
        [ 5, 11]])



