<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20with%20PyTorch/PyTorch%20Basics/CUDA_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
def describe(x):
  print('타입: {}'.format(x.type()))
  print('크기: {}'.format(x.shape))
  print('값: \n{}'.format(x))

In [2]:
print(torch.cuda.is_available())

True


In [5]:
device = torch.device("cuda" if torch.cuda.is_available else 'cpu')
print(device)

cuda


In [13]:
x = torch.rand(3,3).to(device)
describe(x)

타입: torch.cuda.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.0561, 0.9016, 0.2382],
        [0.8855, 0.3022, 0.7462],
        [0.8978, 0.3549, 0.4465]], device='cuda:0')


error occurs when you try to operate cuda tensor and tensor 


In [14]:
y = torch.rand(3,3)
x + y

RuntimeError: ignored

In [15]:
x + y.to(device)

tensor([[0.4912, 1.2162, 1.0135],
        [1.5814, 0.6893, 0.8377],
        [1.1708, 0.4523, 1.2751]], device='cuda:0')

In [27]:
import numpy as np
a = np.array([[3,6,3],
              [7,2,2],
              [2,6,1]])
x + a

TypeError: ignored

In [30]:
x + torch.FloatTensor(a).to(device)

tensor([[3.0561, 6.9016, 3.2382],
        [7.8855, 2.3022, 2.7462],
        [2.8978, 6.3549, 1.4465]], device='cuda:0')