<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20with%20PyTorch/PyTorch%20Basics/Indexing%2C_Slicing%2C_Concatenation%2C_Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
def describe(x):
  print('타입: {}'.format(x.type()))
  print('크기: {}'.format(x.shape))
  print('값: \n{}'.format(x))
  print('\n\n')

In [39]:
x = torch.arange(6).view(2,3)
describe(x)

describe(x[:1,:2])

describe(x[:2,1])

describe(x[0,1])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])



타입: torch.LongTensor
크기: torch.Size([1, 2])
값: 
tensor([[0, 1]])



타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([1, 4])



타입: torch.LongTensor
크기: torch.Size([])
값: 
1





In [22]:
describe(x)

indices = torch.LongTensor([0,2]) #토치 함수를 사용할 때 LongTensor를 필수로 사용해야함
describe(torch.index_select(x, dim=1, index=indices))#dim=1(열)에서 index = 0, index = 2인 값을 출력

indices = torch.LongTensor([0,0,1])
describe(torch.index_select(x, dim=0, index=indices))#dim=0(행)에서 index = 0, index = 0, index = 1인 값을 출력

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])



타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])



타입: torch.LongTensor
크기: torch.Size([3, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2],
        [3, 4, 5]])





In [30]:
x = torch.arange(6).view(2,3)
describe(x)

describe(torch.cat((x,x), dim=0))

describe(torch.cat([x,x], dim=1))

describe(torch.stack([x,x,torch.add(x,1)]))

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])



타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])



타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])



타입: torch.LongTensor
크기: torch.Size([3, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]],

        [[1, 2, 3],
         [4, 5, 6]]])





In [38]:
x1 = torch.arange(6).view(2,3).float()
describe(x1)

x2 = torch.ones(3,2)
x2[:, 1] += 1
describe(x2)

describe(torch.matmul(x1,x2)) #==torch.mm(x1,x2)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])



타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])



타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])



