<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20with%20PyTorch/PyTorch%20Basics/Making_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#tensor
def describe(x):
  print('타입: {}'.format(type(x)))
  print('크기: {}'.format(x.shape))
  print('값: \n{}'.format(x))
  print('\n\n')

print('#  torch.Tensor(2,3)')
describe(torch.Tensor(2,3)) #랜덤값으로 텐서 초기화

print('#  torch.rand(2,3)')
describe(torch.rand(2,3)) #[0,1) 균등 분포

print('#  torch.randn(2,3)')
describe(torch.randn(2,3)) #표준 정규 분포

#  torch.Tensor(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[4.5225e-34, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])



#  torch.rand(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[0.9037, 0.8461, 0.1016],
        [0.8311, 0.0226, 0.1869]])



#  torch.randn(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[ 0.0285,  0.6910,  0.8192],
        [-1.9130, -2.2884, -0.2897]])





In [ ]:
#fill_메서드: 텐서를 특정 값으로 채우는 데 사용
#언더 바(_)가 있는 파이토치 인-플레이스 메서드는 텐서값을 바꾸는 연산을 의미함

print('#  torch.zeros(2,3)')
x = torch.zeros(2,3)
describe(x)

print('#  torch.ones(2,3)')
x = torch.ones(2,3)
describe(x)

print('#  x.fill_(5)')
x.fill_(5)
describe(x)

#  torch.zeros(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



#  torch.ones(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])



#  x.fill_(5)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])





In [ ]:
#입력값으로 파이썬 리스트를 전달할 수 있음
x = torch.Tensor([[1,2,3],
                 [4,5,6]])

describe(x)

타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])





In [ ]:
import numpy as np

In [ ]:
#torch.from_numpy()를 통해 넘파이 텐서를 파이토치 텐서 자료형으로 변경할 수 있음

numpy_tensor = np.random.rand(2,3)
describe(numpy_tensor)

x = torch.from_numpy(numpy_tensor)
describe(x)

타입: <class 'numpy.ndarray'>
크기: (2, 3)
값: 
[[0.47839097 0.18268031 0.11682407]
 [0.19667136 0.94933177 0.47867993]]



타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[0.4784, 0.1827, 0.1168],
        [0.1967, 0.9493, 0.4787]], dtype=torch.float64)



