<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20with%20PyTorch/PyTorch%20Basics/Making_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [25]:
#tensor
def describe(x):
  print('타입: {}'.format(type(x)))
  print('크기: {}'.format(x.shape))
  print('값: \n{}'.format(x))
  print('\n\n')

print('#  torch.Tensor(2,3)')
describe(torch.Tensor(2,3)) #랜덤값으로 텐서 초기화

print('#  torch.rand(2,3)')
describe(torch.rand(2,3)) #[0,1) 균등 분포

print('#  torch.randn(2,3)')
describe(torch.randn(2,3)) #표준 정규 분포

#  torch.Tensor(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[7.1204e-35, 0.0000e+00, 1.5554e-43],
        [1.5975e-43, 1.3873e-43, 1.4574e-43]])



#  torch.rand(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[0.4039, 0.4781, 0.9857],
        [0.3492, 0.2211, 0.8943]])



#  torch.randn(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[ 0.1675,  1.7533, -0.3279],
        [-0.5150,  0.1360,  0.4148]])





In [24]:
#fill_메서드: 텐서를 특정 값으로 채우는 데 사용
#언더 바(_)가 있는 파이토치 인-플레이스 메서드는 텐서값을 바꾸는 연산을 의미함

print('#  torch.zeros(2,3)')
x = torch.zeros(2,3)
describe(x)

print('#  torch.ones(2,3)')
x = torch.ones(2,3)
describe(x)

print('#  x.fill_(5)')
x.fill_(5)
describe(x)

#  torch.zeros(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



#  torch.ones(2,3)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])



#  x.fill_(5)
타입: <class 'torch.Tensor'>
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])



