<a href="https://colab.research.google.com/github/do-huni/NLP_practice/blob/main/OREILLY/NLP%20with%20PyTorch/PyTorch%20Basics/Tensor_and_Computational_Graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
def describe(x):
  print('타입: {}'.format(x.type()))
  print('크기: {}'.format(x.shape))
  print('값: \n{}'.format(x))
    

In [33]:
x = torch.ones(2,2, requires_grad =True)
describe(x)
print(f'{x.grad is None = }')
print('\n\n')

y = (x+2) * (x+5) + 3
describe(y)
print(f'{x.grad is None = }')
print('\n\n')

z = y.max()
describe(z)
print(f'{x.grad is None = }')
print('\n\n')

print('z.backward()')
z.backward()
print(f'{x.grad is None = }')

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
x.grad is None = True



타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
x.grad is None = True



타입: torch.FloatTensor
크기: torch.Size([])
값: 
21.0
x.grad is None = True



z.backward()
x.grad is None = False


In [36]:
print(x.grad)

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])
